### ISSUE TITLE
Backend Configuration

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#505]
**Is your feature request related to a problem? Please describe.**
There is the need for a centralized configuration file. Right now we use Java Properties to configure the backend. Right now the following properties are configured:

* app.postgres.url
* app.postgres.user
* app.postgres.password
* app.production
* app.import.xml
* app.geocoding.host

**Describe the solution you'd like**
The following yaml/toml config could be used:

```yaml
app:
  production: true
  geocoding:
    nominatim-host: ....
  postgres:
    url: ...
    user: ...
    password: ...
```

The import and geocoding configuration options might be moved to the per-project configuration (#506).
Configuration through Salt Stack will happen in #507.
The configuration file should be placed at `/etc/entitlementcard/config.yaml`. 

* It might be useful to specify a conig file though CLI parameters. If not done in this task, please create a new issue.
* It might be useful to override config options through the CLI. Maybe our CLI framework offers a feature for this.  If not done in this task, please create a new issue.

**Describe alternatives you've considered**
None

**Additional context**
None
