### ISSUE TITLE
Per-project configuration

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#506]
**Is your feature request related to a problem? Please describe.**
Like already mentioned in #505 a per-project configuration is needed. The project configuration should be part of the backend configuration (#505)

**Describe the solution you'd like**
The project configurations could look like this:

```yaml
app:
  projects:
    - id: bayern.ehrenamtskarte.app
      import-url: https://...
      pipeline-name: lbe-bayern
    - id: nuernberg.sozialpass.app
      import-url: https://...
      import-pipeline: null
```

**Describe alternatives you've considered**
Multiple files for each project seems more complicated

**Additional context**
None
