### ISSUE TITLE
Add new categories with icons for Nürnberg 

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#512]
**Is your feature request related to a problem? Please describe.**
If Nürnberg wants different categories for their stores then we would need to add them to:
* The database in the backend
* To the app with corresponding icons
* To the map style with corresponding icons

**Describe the solution you'd like**
Each category must have a unique ID. The categories 0 to 9 are already used by the ehrenamtskarte project. For new categories, currently unused IDs should be used.

For each project the used categories should be defined in the build config:

```yaml
projects:
  - id: nuernberg.sozialpass.app:
    categories: [10, 11, 12, 13]
  - id: bayern.ehrenamtskarte.app:
    categories: [0, 1, 2, 3, 4, 5, 6, 7, 8]
```

These categories are used for the Suche/Liste tab.

They are also used on the map:
* Do not add new icons to the map yet
* Adjust the style.json to map nürnbergs categories to some maki icon: https://github.com/digitalfabrik/ehrenamtskarte-maplibre-style (update the submodule)

**For categories for which we do not yet have a detail header `frontend/assets/detail_header/1.svg` show nothing for now and creata a new task for  each icon!**

**Check how the Sonstige category is used**

**Describe alternatives you've considered**
None

**Additional context**
None
