### ISSUE TITLE
Add build config

### ISSUE THREAD

**Issue by maxammann** [digitalfabrik/entitlementcard#517]
**Is your feature request related to a problem? Please describe.**
Add a build config as YAML or TypeScript file. The tooling around build configs will be written using TypeScript. The reason for this is that we can re-use the tooling from Integreat & Lunes. 

Because each YAML file can be represented as TS object and vice-versa the notation in issues can differ from the actual implementation.

**Describe the solution you'd like**
Create a build config by reusing as much tooling from Integreat as possible. The following snippet shows which information should be included in the build config:

```yaml

projects:
  - id: bayern.ehrenamtskarte.app
    map-data-source: https://tiles.ehrenamtskarte.app/rpc/physical_stores.json
    feature-flags:
      verification: false
    theme: 
      primary-color: #123456
      secondary-color: #123456
    categories: [10, 11, 12, 13]
    android:
      applicaiton-id: ...
      app-name: Ehrenamt
      icon-name: name
    ios:
      bundle-id: ....
      icon-name: name
  - id: nuernberg.sozialpass.app
    feature-flags:
      verification: true
    ...
```

* **It is unclear as of now if we want to use a single build config file or multiple files!** Clarify with the team!

**Describe alternatives you've considered**
None

**Additional context**
None
